@email = gian@example.com
@password = 123456789
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdpYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NzM0MDMxMzMsImV4cCI6MTc3MzQwNDMzM30.sUBu3VWtu4r5vlPhPYQZipctKV-svNimSCYk-AfI-d8
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdpYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NzMzOTQ3Mjd9.sxoSgME9qjQUAsRsVU2N6DAja15RozmqqWtRO5tj80E

### Get all emails
GET http://localhost:4000/users

### Register new user
POST http://localhost:4000/users/register
Content-Type: application/json

{
	"email": "{{email}}",
	"password": "{{password}}"
}

### Login
POST http://localhost:4000/users/login
Content-Type: application/json

{
	"email": "{{email}}",
	"password": "{{password}}"
}

### Refresh token
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "{{refreshToken}}"
}

### Get posts (using the JWT token)
GET http://localhost:3000/posts
Authorization: Bearer {{accessToken}}

### Logout (delete refresh token)
DELETE http://localhost:4000/users/logout
Content-Type: application/json

{
    "token": "{{refreshToken}}"
}