@email = gian@example.com
@password = 123456789
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdpYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NzUxMjEyODIsImV4cCI6MTc3NTEyMjQ4Mn0.jeJI1gE8QRUdAi2Q5vGqb5TvETe3zzza3DBYcZfh1NE
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdpYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NzUxMjEyNjh9.MD4boyddZ6mgNCc0S42qc786EGuDHbTCokc8ukAyOvE

### Get all emails
GET http://localhost:3000/users

### Register new user
POST http://localhost:3000/users/register
Content-Type: application/json

{
	"email": "{{email}}",
	"password": "{{password}}"
}

### Login
POST http://localhost:3000/users/login
Content-Type: application/json

{
	"email": "{{email}}",
	"password": "{{password}}"
}

### Refresh token
POST http://localhost:3000/token
Content-Type: application/json

{
    "token": "{{refreshToken}}"
}

### Create an empty portfolio (using the JWT token)
POST http://localhost:3000/portfolios
Authorization: Bearer {{accessToken}}

### List your own portfolios (using the JWT token)
GET http://localhost:3000/portfolios
Authorization: Bearer {{accessToken}}

### Logout (delete refresh token)
DELETE http://localhost:3000/users/logout
Content-Type: application/json

{
    "token": "{{refreshToken}}"
}